/// Flutter icons MeeduIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MeeduIcons
///      fonts:
///       - asset: fonts/MeeduIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MeeduIcons {
  MeeduIcons._();

  static const _kFontFam = 'MeeduIcons';
  static const String? _kFontPkg = null;

  static const IconData facebook = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smartphone =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
